name: RAPA_CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ls -la
        run: ls -la
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./build/libs/*.war

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile  # 청회는 job에다가 넣어주는 방법을 사용함
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/java:latest #latest를 한 이유는? deploy image 가 새로운 버전을 자동 업데이트 시키기 위해 사용한다.

      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: cluster-1
          location: us-central1-c
          credentials: ${{ secrets.gcp_credentials }}
      
      - name: Deploy-Restart
        run: kubectl rollout restart deployment/tomcat-deploy

      - name: get-all
        run: kubectl get all